import { trainingProgramCatalog } from "@/lib/training-programs";

export const institute = {
  name: "API CULTURE",
  legalName: "API Culture Technology Center (Bee Keeping)",
  parent:
    "National Institute of Rural Development & Panchayati Raj, Ministry of Rural Development, Government of India",
  address:
    "\"Honey House\", #12 & 13, CIAT-RTP, Rajendranagar, Hyderabad - 500 030, Telangana, India",
  stateAddress:
    "\"Bee House\", Khadi Gramodyog Maha Vidyalaya (KGMV), Rajendranagar, Hyderabad - 500 030, Telangana, India",
  offices: [
    {
      label: "Central Office",
      address: "\"Honey House\", #12 & 13, CIAT-RTP, Rajendranagar, Hyderabad - 500 030, Telangana, India",
      mapsUrl: "https://maps.app.goo.gl/CnucEbmm6us5LTDBA",
    },
    {
      label: "State Office",
      address: "\"Bee House\", Khadi Gramodyog Maha Vidyalaya (KGMV), Rajendranagar, Hyderabad - 500 030, Telangana, India",
      mapsUrl: "https://maps.app.goo.gl/MouDG368iNNpZjYE9",
    },
  ],
  officeHours: "9:30 AM to 5:30 PM",
  trainingHours: "10:00 AM to 5:00 PM",
  trainingLocation: "ATC's Training Hall",
  phone: ["040-24017766", "040-29387766", "9395507766"],
  email: "info@apiculture.in",
  website: "https://www.apiculture.in",
};

export const fallbackPrograms = trainingProgramCatalog.map((program) => ({
  id: program.id,
  title: program.title,
  slug: program.slug,
  summary: program.summary,
  description: program.description,
  duration: program.duration,
  level: program.level,
  fee: program.fee,
  capacity: program.capacity,
  batchStartsAt: program.batchStartsAt ? new Date(program.batchStartsAt) : null,
  enrollmentClosed: program.enrollmentClosed,
  popupEnabled: program.popupEnabled,
  published: program.published,
  createdAt: new Date("2026-01-01"),
  updatedAt: new Date("2026-01-01"),
}));

export const fallbackEvents = [];

export const fallbackArticles = [
  {
    id: "article-honey-price-crisis-response",
    title: "When Honey Prices Fall Below Cost, Beekeepers Need a Local Recovery Plan",
    slug: "honey-prices-below-cost-local-recovery-plan",
    excerpt:
      "A field-level response to low honey prices, falling yields, adulteration pressure, and export disruption affecting Indian beekeepers.",
    body:
      "Recent reporting from Punjab shows why beekeeping support must move beyond training alone. Per-hive yields have been reported far below earlier averages, input costs have risen, and market prices have not kept pace. When genuine honey is forced to compete with cheap blended or adulterated product, the beekeeper who maintains colonies properly is the first person punished by the market.\n\nThe practical solution is to organize honey around proof, aggregation, and alternate income. Each beekeeper should keep a simple batch ledger: colony count, floral source, harvest date, moisture reading, processing date, and buyer details. Farmer groups can aggregate only tested batches, separate honey by floral source, and negotiate as a quality lot instead of as distress stock. Technology centers can support this by offering moisture testing, batch coding, label guidance, and buyer days where verified honey is shown directly to local retailers, institutions, and bulk buyers.\n\nThe second income line is pollination service. Crop farmers need stronger pollination, and beekeepers need revenue before honey is harvested. A local pollination contract should record crop, acreage, colony strength, placement date, spray restrictions, water/shade responsibility, and payment schedule. This turns the beekeeper from a commodity seller into a farm service partner.",
    category: "Market solution",
    publishedAt: new Date("2026-08-06T09:00:00.000Z"),
    authorName: "API CULTURE Editorial Desk",
    authorRole: "Market and Field Support",
    mediaUrl: "/gallery/profile-2025/honey-jars-quality.jpg",
    mediaObjectKey: "gallery/profile-2025/honey-jars-quality.jpg",
    mediaType: "IMAGE",
    externalLink: "https://timesofindia.indiatimes.com/city/ludhiana/sticky-end-for-punjabs-bee-farmers-apiaries-empty-as-honey-industry-sours-/articleshow/130837205.cms",
    keyPoints: "Batch-level proof\nGroup aggregation\nPollination contracts",
    seoTitle: "Honey Price Crisis Recovery Plan for Beekeepers",
    metaDescription: "A practical plan for beekeepers facing low honey prices, adulteration pressure, and falling colony yields.",
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "article-climate-bloom-calendar",
    title: "Climate-Interrupted Nectar Flow: Build a Bloom Calendar Before Moving Hives",
    slug: "climate-interrupted-nectar-flow-bloom-calendar",
    excerpt:
      "Migratory beekeeping is becoming more weather-sensitive, so hive movement needs local bloom intelligence and safer route planning.",
    body:
      "Migratory beekeepers in India have long followed flowering windows, but extreme weather is making that timing less dependable. Reports from Assam describe beekeepers working mustard fields while facing floods, stronger monsoons, heat, and development pressure that can disturb nectar flow and colony behavior. The problem is not only movement; it is moving without fresh local information.\n\nA workable solution is a district bloom calendar maintained with farmer groups, horticulture officers, and beekeepers. It should track major flowering crops, expected bloom weeks, rainfall disruptions, pesticide-heavy windows, water access, shade availability, and safe parking points for colonies. Before a beekeeper moves boxes, the group can confirm three checks: bloom is open, spray risk is manageable, and colonies have a safe resting site.\n\nTechnology centers can make this simple. A printed seasonal route map, a WhatsApp update group, and a weekly field call during migration months are enough to prevent many bad moves. In hotter periods, beekeepers should add shade screens, water trays, short inspection windows, and transport at cooler hours. Where local bee species are important for ecology, training should also include how to support native pollinators instead of relying only on migratory colonies.",
    category: "Climate readiness",
    publishedAt: new Date("2026-08-06T08:30:00.000Z"),
    authorName: "API CULTURE Training Wing",
    authorRole: "Climate-Resilient Apiary Practice",
    mediaUrl: "/gallery/profile-2025/hive-boxes-field-visit.jpg",
    mediaObjectKey: "gallery/profile-2025/hive-boxes-field-visit.jpg",
    mediaType: "IMAGE",
    externalLink: "https://apnews.com/article/india-honey-bees-beekeepers-climate-change-d38a29dbfaf2d67aca1455241ae28eda",
    keyPoints: "Bloom calendar\nWeather-safe movement\nWater and shade planning",
    seoTitle: "Climate-Resilient Bloom Calendar for Beekeepers",
    metaDescription: "How beekeepers can plan hive movement around changing bloom, weather, water, and pesticide conditions.",
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "article-pesticide-spray-window-agreement",
    title: "Pesticide Exposure Near Farms: Use a Spray-Window Agreement Before Colonies Arrive",
    slug: "pesticide-exposure-spray-window-agreement",
    excerpt:
      "A simple farmer-beekeeper agreement can reduce bee poisoning, protect crop pollination, and prevent avoidable colony loss.",
    body:
      "Pesticide exposure remains one of the most practical risks for beekeepers working near crop fields. FAO guidance highlights the need for stronger risk mitigation to protect pollinators, and field experience shows the same lesson: most losses are easiest to prevent before the spray happens.\n\nThe solution is a spray-window agreement between the crop farmer and beekeeper. Before colonies are placed, both sides should record the crop stage, expected spray dates, product name if known, time of application, wind condition, and contact number for warning. Spraying should be avoided during active bee foraging. When treatment is unavoidable, the farmer should notify the beekeeper early enough to close, cover, or temporarily shift colonies, and should choose the least harmful option allowed by label directions and local advisory guidance.\n\nTechnology centers can support this by giving trainees a one-page agreement format and teaching both sides how to read pesticide labels, watch drift, maintain clean drinking water for colonies, and place hives away from direct spray paths. The result is not anti-farmer and not anti-crop protection; it is coordinated crop protection that does not destroy the pollination service the crop also needs.",
    category: "Pollinator protection",
    publishedAt: new Date("2026-08-05T10:00:00.000Z"),
    authorName: "API CULTURE Extension Team",
    authorRole: "Crop Interface Support",
    mediaUrl: "/gallery/profile-2025/field-apiary-demonstration.jpg",
    mediaObjectKey: "gallery/profile-2025/field-apiary-demonstration.jpg",
    mediaType: "IMAGE",
    externalLink: "https://www.fao.org/publications/news-archive/detail/the-importance-of-bee-ing-together/en",
    keyPoints: "Advance spray notice\nAvoid active foraging hours\nReduce drift and exposure",
    seoTitle: "Spray-Window Agreement for Bee Safety",
    metaDescription: "A practical farmer-beekeeper agreement to reduce pesticide exposure and protect pollination.",
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "article-varroa-monitoring-calendar",
    title: "Varroa and Colony Health: A Monthly Monitoring Calendar for Apiaries",
    slug: "varroa-colony-health-monthly-monitoring-calendar",
    excerpt:
      "Colony health improves when mite pressure is measured early, recorded clearly, and handled through integrated management.",
    body:
      "Varroa mites are a major colony health threat because they weaken bees directly and spread damaging viruses. Research on resistant honey bee stocks shows why long-term resilience matters: breeding and selecting stronger colonies can reduce dependence on repeated chemical interventions. For everyday beekeepers, the first step is not a new product; it is regular monitoring.\n\nA monthly apiary calendar should include colony strength, brood pattern, visible deformities, mite count method used, treatment decision, queen condition, feed status, and follow-up date. Weak or newly purchased colonies should be quarantined and checked before joining the main apiary. Old comb should be rotated out gradually, hive tools should be cleaned between suspicious colonies, and any treatment should follow approved local guidance rather than guesswork.\n\nTechnology centers can teach this as a habit: inspect, count, decide, record, and recheck. When records show repeated mite pressure in one colony line, that colony should not be used for multiplication. Preference should go to hygienic, locally adapted, productive colonies that survive with lower intervention.",
    category: "Colony health",
    publishedAt: new Date("2026-08-04T09:30:00.000Z"),
    authorName: "API CULTURE Apiary Team",
    authorRole: "Colony Health Support",
    mediaUrl: "/gallery/profile-2025/frame-inspection-closeup.jpg",
    mediaObjectKey: "gallery/profile-2025/frame-inspection-closeup.jpg",
    mediaType: "IMAGE",
    externalLink: "https://www.ars.usda.gov/news-events/news/research-news/2022/ars-developed-varroa-resistant-honey-bees-better-winter-survivors/",
    keyPoints: "Monthly mite checks\nQuarantine weak colonies\nSelect resilient stock",
    seoTitle: "Varroa Monitoring Calendar for Beekeepers",
    metaDescription: "A monthly colony health calendar for monitoring Varroa risk and strengthening apiary resilience.",
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "article-honey-trust-traceability-labels",
    title: "Honey Trust After Label Scrutiny: Trace Every Batch Before You Claim Quality",
    slug: "honey-trust-traceability-labels",
    excerpt:
      "Recent scrutiny of purity claims shows why small honey producers need batch records, traceability, and careful labels.",
    body:
      "Recent action and legal challenges around food label claims in India show that trust in honey cannot depend on bold words alone. For small producers, this is an opportunity. A beekeeper who can prove source, harvest date, moisture, processing, and packing details has a stronger story than a generic label claim.\n\nThe solution starts with traceability. Each batch should receive a lot number connected to apiary location, floral source, harvest date, extraction date, moisture reading, storage container, and buyer or packer. Producers should register and update required details on official traceability systems where applicable, including Madhukranti, and should avoid unverified claims such as absolute purity statements unless the claim is legally allowed and backed by test records.\n\nA practical label should say what can be proven: net quantity, batch number, date, contact, FSSAI details where required, floral or regional source when recorded, and storage guidance. Technology centers can add value by helping farmer groups standardize batch sheets, arrange periodic lab tests, and explain label rules before printing. The goal is simple: let real honey win through evidence.",
    category: "Quality and traceability",
    publishedAt: new Date("2026-08-03T11:00:00.000Z"),
    authorName: "API CULTURE Quality Desk",
    authorRole: "Honey Value Chain Support",
    mediaUrl: "/gallery/profile-2025/comb-foundation-demonstration.jpg",
    mediaObjectKey: "gallery/profile-2025/comb-foundation-demonstration.jpg",
    mediaType: "IMAGE",
    externalLink: "https://madhukranti.in/",
    keyPoints: "Batch lot numbers\nMadhukranti traceability\nEvidence-based labels",
    seoTitle: "Honey Traceability and Label Trust",
    metaDescription: "How honey producers can build consumer trust through traceability, batch records, testing, and compliant labels.",
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
];

export const fallbackGalleryImages = [
  {
    id: "gallery-profile-bees-on-comb",
    url: "/gallery/profile-2025/honey-bees-on-comb.jpg",
    caption: "Close observation of colony activity and brood-area strength.",
    date: new Date("2025-01-01"),
    place: "API Culture Technology Center profile archive",
    category: "Apiary practice",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-frame-inspection",
    url: "/gallery/profile-2025/frame-inspection-closeup.jpg",
    caption: "Hands-on frame handling and colony inspection practice.",
    date: new Date("2025-01-02"),
    place: "API Culture Technology Center profile archive",
    category: "Training",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-field-frame-training",
    url: "/gallery/profile-2025/field-frame-training.jpg",
    caption: "Practical hive-frame demonstration for trainees and farmers.",
    date: new Date("2025-01-03"),
    place: "API Culture Technology Center profile archive",
    category: "Field demonstration",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-comb-foundation",
    url: "/gallery/profile-2025/comb-foundation-demonstration.jpg",
    caption: "Comb foundation and equipment handling for better hive management.",
    date: new Date("2025-01-04"),
    place: "API Culture Technology Center profile archive",
    category: "Equipment",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-honey-quality",
    url: "/gallery/profile-2025/honey-jars-quality.jpg",
    caption: "Honey presentation linked to quality, traceability, and value addition.",
    date: new Date("2025-01-05"),
    place: "API Culture Technology Center profile archive",
    category: "Honey value chain",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-field-apiary-demo",
    url: "/gallery/profile-2025/field-apiary-demonstration.jpg",
    caption: "Outdoor training with farmers around hive placement and field handling.",
    date: new Date("2025-01-06"),
    place: "API Culture Technology Center profile archive",
    category: "Farmer training",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-apiary-inspection",
    url: "/gallery/profile-2025/apiary-inspection-with-media.jpg",
    caption: "Field-level inspection and documentation of hive management practices.",
    date: new Date("2025-01-07"),
    place: "API Culture Technology Center profile archive",
    category: "Inspection",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
  {
    id: "gallery-profile-hive-boxes",
    url: "/gallery/profile-2025/hive-boxes-field-visit.jpg",
    caption: "Trainees reviewing hive placement and colony access in field conditions.",
    date: new Date("2025-01-08"),
    place: "API Culture Technology Center profile archive",
    category: "Apiary setup",
    year: 2025,
    published: true,
    createdAt: new Date("2026-08-06"),
    updatedAt: new Date("2026-08-06"),
  },
];

export const fallbackApplications = [];
