import { trainingProgramCatalog } from "@/lib/training-programs";

export const institute = {
  name: "API CULTURE",
  legalName: "API Culture Technology Center (Bee Keeping)",
  parent:
    "National Institute of Rural Development & Panchayati Raj, Ministry of Rural Development, Government of India",
  address:
    "#12 & 13, CIAT-RTP, Rajendranagar, Hyderabad - 500 030, Telangana, India",
  stateAddress:
    "'Bee House', Khadi Gramodyog Maha Vidyalaya (KGMV), Rajendranagar, Hyderabad - 500 030, Telangana, India",
  offices: [
    {
      label: "Central Office",
      address: "#12 & 13, CIAT-RTP, Rajendranagar, Hyderabad - 500 030, Telangana, India",
      mapsUrl: "https://maps.app.goo.gl/CnucEbmm6us5LTDBA",
    },
    {
      label: "State Office",
      address: "'Bee House', Khadi Gramodyog Maha Vidyalaya (KGMV), Rajendranagar, Hyderabad - 500 030, Telangana, India",
      mapsUrl: "https://maps.app.goo.gl/MouDG368iNNpZjYE9",
    },
  ],
  officeHours: "9:30 AM to 5:30 PM",
  trainingHours: "10:00 AM to 5:00 PM",
  trainingLocation: "ATC's Training Hall",
  phone: ["040-24017766", "9395507766"],
  email: "info@apiculture.in",
  website: "https://www.apiculture.in",
};

export const fallbackPrograms = trainingProgramCatalog.map((program) => ({
  id: program.id,
  title: program.title,
  slug: program.slug,
  summary: program.summary,
  description: program.description,
  duration: program.duration,
  level: program.level,
  fee: program.fee,
  capacity: program.capacity,
  batchStartsAt: new Date(program.batchStartsAt),
  enrollmentClosed: program.enrollmentClosed,
  popupEnabled: program.popupEnabled,
  published: program.published,
  createdAt: new Date("2026-01-01"),
  updatedAt: new Date("2026-01-01"),
}));

export const fallbackEvents = [
  {
    id: "event-orientation",
    title: "Apiculture Technology Orientation",
    slug: "apiculture-technology-orientation",
    summary:
      "Open orientation on modern beekeeping, honey value chains, and rural enterprise opportunities.",
    description:
      "A public orientation for prospective trainees, farmer groups, and partner institutions. Sessions include center briefing, equipment demonstrations, and guidance on training enrollment.",
    location: "ATC's Training Hall, Rajendranagar, Hyderabad",
    startsAt: new Date("2026-06-12T10:00:00.000Z"),
    endsAt: new Date("2026-06-12T13:00:00.000Z"),
    status: "UPCOMING",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
];

export const fallbackArticles = [
  {
    id: "article-queen-strength",
    title: "Managing Bee Colonies in High Temperature Without Losing Strength",
    slug: "managing-bee-colonies-in-high-temperature-without-losing-strength",
    excerpt: "A practical field note on summer hive care, airflow, shade, and hydration management for colony stability.",
    body:
      "High temperature can place major pressure on colonies when airflow, shade, and water access are not managed in time. This article outlines simple steps for reducing heat stress, keeping brood areas stable, protecting worker activity, and avoiding unnecessary colony weakening during peak seasonal stress.\n\nThe guidance is written for field teams, trainees, and rural beekeepers who need direct, practical actions rather than theory-heavy instructions.",
    category: "Field management",
    publishedAt: new Date("2026-06-14T10:00:00.000Z"),
    authorName: "API CULTURE Editorial Desk",
    authorRole: "Training and Field Team",
    mediaUrl: "/field-beekeeping.jpg",
    mediaObjectKey: "fallback/articles/field-beekeeping.jpg",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Shade near apiary\nWater source nearby\nReduce comb overheating",
    seoTitle: "Managing Bee Colonies in High Temperature",
    metaDescription: "Practical field methods for keeping bee colonies stable during high summer temperatures.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "article-honey-production",
    title: "How To Select a Bee Honey Production During Monsoon Season in Beekeeping",
    slug: "how-to-select-a-bee-honey-production-during-monsoon-season-in-beekeeping",
    excerpt: "Monsoon conditions change forage, moisture, and disease pressure, so honey production decisions must stay seasonal.",
    body:
      "Monsoon season requires more careful honey production planning because forage conditions, hive moisture, and colony strength may shift quickly. This article helps trainees understand when to hold back, when to inspect, and how to judge whether conditions are suitable for honey-focused management.\n\nThe note is meant for application in training discussions, field visits, and extension support.",
    category: "Seasonal guidance",
    publishedAt: new Date("2026-06-18T09:30:00.000Z"),
    authorName: "API CULTURE Training Wing",
    authorRole: "Seasonal Practice Unit",
    mediaUrl: "/scientific-foundation-bg.jpg",
    mediaObjectKey: "fallback/articles/scientific-foundation-bg.jpg",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Check forage availability\nWatch humidity levels\nPrevent fungal pressure",
    seoTitle: "Monsoon Season Honey Production in Beekeeping",
    metaDescription: "Seasonal considerations for planning honey production during monsoon conditions.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "article-pollination",
    title: "Poor Pollination in Crop Fields: How Better Bee Placement Can Improve Results",
    slug: "poor-pollination-in-crop-fields-how-better-bee-placement-can-improve-results",
    excerpt: "Placement strategy matters. Small shifts in colony position can improve pollination effectiveness across crop fields.",
    body:
      "When pollination results remain weak, the issue is not always colony count alone. Field placement, distance from bloom concentration, shade, access routes, and crop timing all influence how well bees support pollination activity.\n\nThis article provides a field-oriented explanation that can be used in training sessions and institutional advisory work.",
    category: "Pollination support",
    publishedAt: new Date("2026-06-22T08:45:00.000Z"),
    authorName: "API CULTURE Extension Team",
    authorRole: "Crop Interface Support",
    mediaUrl: "/hero-background-original.mp4",
    mediaObjectKey: "fallback/articles/hero-background-original.mp4",
    mediaType: "VIDEO",
    externalLink: "",
    keyPoints: "Place near bloom density\nAvoid blocked flight paths\nReview field spread",
    seoTitle: "Better Bee Placement for Crop Pollination",
    metaDescription: "Why bee placement strategy can improve pollination performance across crop fields.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-smoker-handling",
    title: "Smoker Handling Mistakes That Make Hive Inspections Harder",
    slug: "smoker-handling-mistakes-that-make-hive-inspections-harder",
    excerpt: "A testing article on calm smoke use, inspection rhythm, and common mistakes that disturb colonies.",
    body:
      "Smoke should support a calm inspection, not cover up poor handling. New beekeepers often use too much smoke, direct it too close to the cluster, or keep the hive open longer than needed.\n\nThis testing article explains how a steady smoker, gentle frame movement, and short inspection windows can make training sessions easier to manage.",
    category: "Hive practice",
    publishedAt: new Date("2026-07-02T09:00:00.000Z"),
    authorName: "API CULTURE Training Desk",
    authorRole: "Testing Article",
    mediaUrl: "/beekeeping-training-program.png",
    mediaObjectKey: "fallback/articles/beekeeping-training-program.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Use cool smoke\nAvoid over-smoking\nKeep inspections short",
    seoTitle: "Smoker Handling Mistakes in Beekeeping",
    metaDescription: "Testing article for smoker handling and hive inspection UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-honey-hygiene",
    title: "Honey Hygiene Checklist Before Extraction Day",
    slug: "honey-hygiene-checklist-before-extraction-day",
    excerpt: "A quick newsroom-style checklist for clean rooms, dry equipment, and disciplined handling before extraction.",
    body:
      "Extraction day becomes easier when hygiene preparation starts before supers reach the room. Floors, knives, containers, sieves, and settling tanks all need a simple checklist.\n\nThis testing story gives the article page a practical honey-processing topic with enough text to evaluate spacing, cards, and related story blocks.",
    category: "Honey processing",
    publishedAt: new Date("2026-07-05T11:20:00.000Z"),
    authorName: "API CULTURE Processing Unit",
    authorRole: "Testing Article",
    mediaUrl: "/honey-processing-training-program.png",
    mediaObjectKey: "fallback/articles/honey-processing-training-program.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Dry tools first\nUse food-grade containers\nFilter in stages",
    seoTitle: "Honey Hygiene Checklist",
    metaDescription: "Testing article for honey processing UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-queen-cell-selection",
    title: "Queen Cell Selection: What Trainees Should Observe First",
    slug: "queen-cell-selection-what-trainees-should-observe-first",
    excerpt: "A field note on reading queen cell placement, colony mood, and timing during queen rearing practice.",
    body:
      "Queen rearing training depends on careful observation. Cell placement, larval age, colony strength, and weather timing all affect the learning outcome.\n\nThis sample article helps test longer article titles, queen-rearing imagery, and category filters across the article index.",
    category: "Queen rearing",
    publishedAt: new Date("2026-07-08T08:10:00.000Z"),
    authorName: "API CULTURE Queen Rearing Desk",
    authorRole: "Testing Article",
    mediaUrl: "/queen-rearing-bg.jpg",
    mediaObjectKey: "fallback/articles/queen-rearing-bg.jpg",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Check larval age\nRead colony strength\nRecord timing",
    seoTitle: "Queen Cell Selection",
    metaDescription: "Testing article for queen rearing article UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-rural-youth-apiary",
    title: "How Rural Youth Can Start a Small Training Apiary",
    slug: "how-rural-youth-can-start-a-small-training-apiary",
    excerpt: "A practical testing story about starter colonies, equipment planning, and basic apiary discipline.",
    body:
      "A small training apiary does not need to begin with too many colonies. It needs clear placement, record keeping, protective equipment, and regular guidance.\n\nThis fake article is included only to test the public articles UI with enterprise-style content and realistic beekeeping vocabulary.",
    category: "Rural enterprise",
    publishedAt: new Date("2026-07-11T10:45:00.000Z"),
    authorName: "API CULTURE Enterprise Cell",
    authorRole: "Testing Article",
    mediaUrl: "/why-matters-bee-bloom-v2.png",
    mediaObjectKey: "fallback/articles/why-matters-bee-bloom-v2.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Start small\nKeep records\nPlan equipment",
    seoTitle: "Small Training Apiary",
    metaDescription: "Testing article for rural enterprise UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-monsoon-feeding",
    title: "Monsoon Feeding: When Support Helps and When It Creates Risk",
    slug: "monsoon-feeding-when-support-helps-and-when-it-creates-risk",
    excerpt: "A seasonal fake article for testing article filters, discussing feed timing, moisture, and colony pressure.",
    body:
      "Feeding during monsoon conditions must be handled with care. Wrong timing can attract robbing, add moisture stress, or hide deeper colony weakness.\n\nThis testing article adds another seasonal story to evaluate how the listing page behaves with multiple cards in one category.",
    category: "Seasonal guidance",
    publishedAt: new Date("2026-07-14T12:00:00.000Z"),
    authorName: "API CULTURE Seasonal Desk",
    authorRole: "Testing Article",
    mediaUrl: "/quote-honey-bee.jpg",
    mediaObjectKey: "fallback/articles/quote-honey-bee.jpg",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Watch moisture\nAvoid robbing\nFeed only when needed",
    seoTitle: "Monsoon Feeding Risks",
    metaDescription: "Testing article for monsoon guidance UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-batch-day-plan",
    title: "A Practical Day Plan for Beekeeping Training Batches",
    slug: "a-practical-day-plan-for-beekeeping-training-batches",
    excerpt: "A sample operations article on balancing classroom instruction, demonstrations, and hands-on practice.",
    body:
      "Strong training days need rhythm. A batch can move from classroom briefing to demonstration, then to supervised practice, reflection, and record updates.\n\nThis fake article is useful for testing operational article titles and list density on the public articles page.",
    category: "Training operations",
    publishedAt: new Date("2026-07-17T09:35:00.000Z"),
    authorName: "API CULTURE Operations Desk",
    authorRole: "Testing Article",
    mediaUrl: "/contact-center-visual.jpg",
    mediaObjectKey: "fallback/articles/contact-center-visual.jpg",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Brief first\nPractice safely\nClose with records",
    seoTitle: "Beekeeping Training Day Plan",
    metaDescription: "Testing article for training operations UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-royal-jelly-room",
    title: "Royal Jelly Room Setup: Small Details That Matter",
    slug: "royal-jelly-room-setup-small-details-that-matter",
    excerpt: "A testing story about room hygiene, tools, timing, and controlled handling during royal jelly training.",
    body:
      "Royal jelly production requires discipline in room setup and handling. Tools, surfaces, labels, and timing must stay organized from the first demonstration.\n\nThis sample article adds premium-program content to the listing page and tests how category badges behave with longer labels.",
    category: "Royal jelly",
    publishedAt: new Date("2026-07-20T08:55:00.000Z"),
    authorName: "API CULTURE Royal Jelly Desk",
    authorRole: "Testing Article",
    mediaUrl: "/royal-jelly-production-training.png",
    mediaObjectKey: "fallback/articles/royal-jelly-production-training.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Prepare tools\nLabel batches\nProtect hygiene",
    seoTitle: "Royal Jelly Room Setup",
    metaDescription: "Testing article for royal jelly UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-campus-field-note",
    title: "Campus Field Note: What Visitors Notice First at the Center",
    slug: "campus-field-note-what-visitors-notice-first-at-the-center",
    excerpt: "A campus-focused fake article for testing gallery-like article cards and center identity content.",
    body:
      "Visitors often understand the center through small signals: signage, apiary layout, demonstration areas, and the way trainers explain each station.\n\nThis testing article gives the articles page a campus story that sits between news, gallery, and institutional content.",
    category: "Campus notes",
    publishedAt: new Date("2026-07-23T13:15:00.000Z"),
    authorName: "API CULTURE Editorial Desk",
    authorRole: "Testing Article",
    mediaUrl: "/honey-house-signboard.jpg",
    mediaObjectKey: "fallback/articles/honey-house-signboard.jpg",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Clear signage\nVisible apiary\nGuided stations",
    seoTitle: "Campus Field Note",
    metaDescription: "Testing article for campus article UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-equipment-starter-kit",
    title: "Starter Equipment Kit: What New Learners Actually Need",
    slug: "starter-equipment-kit-what-new-learners-actually-need",
    excerpt: "A practical fake article about avoiding unnecessary purchases and choosing essential beginner tools.",
    body:
      "New learners often want to buy too much equipment too quickly. A better starter kit focuses on protective gear, hive tools, smoker basics, and clean containers.\n\nThis article supports UI testing for equipment-related content and search behavior.",
    category: "Equipment",
    publishedAt: new Date("2026-07-26T10:05:00.000Z"),
    authorName: "API CULTURE Equipment Desk",
    authorRole: "Testing Article",
    mediaUrl: "/scientific-beekeeping-icon.png",
    mediaObjectKey: "fallback/articles/scientific-beekeeping-icon.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Buy essentials\nFit protective gear\nMaintain tools",
    seoTitle: "Starter Equipment Kit",
    metaDescription: "Testing article for equipment UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-apiary-records",
    title: "Apiary Records That Help Trainers Spot Problems Early",
    slug: "apiary-records-that-help-trainers-spot-problems-early",
    excerpt: "A record-keeping test article covering colony notes, dates, feeding, queen status, and inspection outcomes.",
    body:
      "Good records turn field impressions into decisions. Dates, queen condition, brood pattern, feed use, and disease signs should be easy to compare across visits.\n\nThis testing article gives the page a documentation-focused story and helps test text-heavy cards.",
    category: "Field management",
    publishedAt: new Date("2026-07-29T09:25:00.000Z"),
    authorName: "API CULTURE Field Team",
    authorRole: "Testing Article",
    mediaUrl: "/about-honeycomb-background.png",
    mediaObjectKey: "fallback/articles/about-honeycomb-background.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Record dates\nTrack queen status\nCompare inspections",
    seoTitle: "Apiary Records",
    metaDescription: "Testing article for records UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-market-ready-honey",
    title: "Market-Ready Honey: Labels, Confidence, and Buyer Trust",
    slug: "market-ready-honey-labels-confidence-and-buyer-trust",
    excerpt: "A sample enterprise article on presentation, basic labeling discipline, and clean customer communication.",
    body:
      "Market confidence begins before the first sale. Clean bottles, readable labels, batch discipline, and honest communication make honey easier to trust.\n\nThis fake article tests business-style stories and how they appear in the related article rail.",
    category: "Rural enterprise",
    publishedAt: new Date("2026-08-01T10:30:00.000Z"),
    authorName: "API CULTURE Enterprise Cell",
    authorRole: "Testing Article",
    mediaUrl: "/quote-honeycomb-background.png",
    mediaObjectKey: "fallback/articles/quote-honeycomb-background.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Clean bottles\nReadable labels\nBatch confidence",
    seoTitle: "Market Ready Honey",
    metaDescription: "Testing article for rural enterprise marketing UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: "test-article-flower-calendar",
    title: "Flowering Calendar Notes Every Beekeeper Should Maintain",
    slug: "flowering-calendar-notes-every-beekeeper-should-maintain",
    excerpt: "A testing article about nectar flow, bloom timing, and seasonal observation for stronger colony decisions.",
    body:
      "A flowering calendar helps beekeepers connect colony behavior with the landscape around them. Bloom timing, weather shifts, and forage gaps all become easier to understand.\n\nThis final fake article gives the listing page another visual card and helps test pagination-like density.",
    category: "Pollination support",
    publishedAt: new Date("2026-08-03T08:00:00.000Z"),
    authorName: "API CULTURE Extension Team",
    authorRole: "Testing Article",
    mediaUrl: "/about-bee-flower-background.png",
    mediaObjectKey: "fallback/articles/about-bee-flower-background.png",
    mediaType: "IMAGE",
    externalLink: "",
    keyPoints: "Map blooms\nTrack forage gaps\nCompare seasons",
    seoTitle: "Flowering Calendar Notes",
    metaDescription: "Testing article for pollination and seasonal UI.",
    published: true,
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
];

export const fallbackGalleryImages = [
  {
    id: "gallery-center-signboard-2025",
    url: "/honey-house-signboard.jpg",
    caption: "Main center signboard at the Rajendranagar campus entrance during the current institutional season.",
    date: new Date("2025-02-12T09:20:00.000Z"),
    place: "ATC's Training Hall, Rajendranagar, Hyderabad",
    category: "CAMPUS_INFRASTRUCTURE",
    year: 2025,
    published: true,
    createdAt: new Date("2025-02-12T09:20:00.000Z"),
    updatedAt: new Date("2025-02-12T09:20:00.000Z"),
  },
  {
    id: "gallery-field-practice-2025",
    url: "/field-beekeeping.jpg",
    caption: "Hands-on field beekeeping practice with live hive handling during a foundation training batch.",
    date: new Date("2025-03-18T11:05:00.000Z"),
    place: "Field training apiary, Hyderabad",
    category: "TRAINING_PROGRAMS",
    year: 2025,
    published: true,
    createdAt: new Date("2025-03-18T11:05:00.000Z"),
    updatedAt: new Date("2025-03-18T11:05:00.000Z"),
  },
  {
    id: "gallery-scientific-foundation-2025",
    url: "/scientific-foundation-bg.jpg",
    caption: "Scientific beekeeping foundation session capturing supervised comb observation and practical instruction.",
    date: new Date("2025-04-06T15:10:00.000Z"),
    place: "Training grounds, Hyderabad campus",
    category: "TRAINING_PROGRAMS",
    year: 2025,
    published: true,
    createdAt: new Date("2025-04-06T15:10:00.000Z"),
    updatedAt: new Date("2025-04-06T15:10:00.000Z"),
  },
  {
    id: "gallery-queen-rearing-2025",
    url: "/queen-rearing-bg.jpg",
    caption: "Advanced queen rearing and colony multiplication batch photographed during controlled instructional work.",
    date: new Date("2025-04-29T14:25:00.000Z"),
    place: "Advanced apiary block, Hyderabad",
    category: "FIELD_VISITS",
    year: 2025,
    published: true,
    createdAt: new Date("2025-04-29T14:25:00.000Z"),
    updatedAt: new Date("2025-04-29T14:25:00.000Z"),
  },
  {
    id: "gallery-kavuri-visit-2024",
    url: "/kavuri-extract-0.png",
    caption: "Institutional review moment recorded during a dignitary interaction and program discussion.",
    date: new Date("2024-11-15T10:00:00.000Z"),
    place: "API CULTURE meeting hall, Hyderabad",
    category: "DIGNITARIES_VISITS",
    year: 2024,
    published: true,
    createdAt: new Date("2024-11-15T10:00:00.000Z"),
    updatedAt: new Date("2024-11-15T10:00:00.000Z"),
  },
  {
    id: "gallery-kavuri-lab-2024",
    url: "/kavuri-extract-1.png",
    caption: "A compact documentation frame showing institutional walkthrough and on-site technical review.",
    date: new Date("2024-10-02T13:35:00.000Z"),
    place: "Technical display area, Hyderabad campus",
    category: "AWARENESS_EVENTS",
    year: 2024,
    published: true,
    createdAt: new Date("2024-10-02T13:35:00.000Z"),
    updatedAt: new Date("2024-10-02T13:35:00.000Z"),
  },
  {
    id: "gallery-kavuri-products-2024",
    url: "/kavuri-extract-2.png",
    caption: "Bee hive product showcase prepared for visitors during awareness and extension activities.",
    date: new Date("2024-08-22T12:40:00.000Z"),
    place: "Extension display desk, Hyderabad",
    category: "BEE_HIVE_PRODUCTS",
    year: 2024,
    published: true,
    createdAt: new Date("2024-08-22T12:40:00.000Z"),
    updatedAt: new Date("2024-08-22T12:40:00.000Z"),
  },
  {
    id: "gallery-kavuri-outreach-2024",
    url: "/kavuri-extract-3.png",
    caption: "Awareness outreach visual from a public-facing center activity focused on practical apiculture learning.",
    date: new Date("2024-07-09T16:05:00.000Z"),
    place: "Community outreach zone, Hyderabad",
    category: "AWARENESS_EVENTS",
    year: 2024,
    published: true,
    createdAt: new Date("2024-07-09T16:05:00.000Z"),
    updatedAt: new Date("2024-07-09T16:05:00.000Z"),
  },
  {
    id: "gallery-campus-archive-2023",
    url: "/honey-house-signboard.jpg",
    caption: "Campus archive frame documenting the center infrastructure during an earlier operational year.",
    date: new Date("2023-12-04T09:45:00.000Z"),
    place: "Rajendranagar campus, Hyderabad",
    category: "CAMPUS_INFRASTRUCTURE",
    year: 2023,
    published: true,
    createdAt: new Date("2023-12-04T09:45:00.000Z"),
    updatedAt: new Date("2023-12-04T09:45:00.000Z"),
  },
  {
    id: "gallery-training-archive-2023",
    url: "/field-beekeeping.jpg",
    caption: "Archived field-learning image showing trainees working close to the apiary under guided supervision.",
    date: new Date("2023-09-13T08:30:00.000Z"),
    place: "Training apiary, Hyderabad district",
    category: "FIELD_VISITS",
    year: 2023,
    published: true,
    createdAt: new Date("2023-09-13T08:30:00.000Z"),
    updatedAt: new Date("2023-09-13T08:30:00.000Z"),
  },
  {
    id: "gallery-products-archive-2023",
    url: "/scientific-foundation-bg.jpg",
    caption: "Documentation frame used in product-linked learning around honey handling and presentation standards.",
    date: new Date("2023-06-21T11:55:00.000Z"),
    place: "Instruction block, Hyderabad",
    category: "BEE_HIVE_PRODUCTS",
    year: 2023,
    published: true,
    createdAt: new Date("2023-06-21T11:55:00.000Z"),
    updatedAt: new Date("2023-06-21T11:55:00.000Z"),
  },
];

function createStudentPhotoDataUri(initials: string, bg: string) {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="640" height="640" viewBox="0 0 640 640">
      <rect width="640" height="640" rx="48" fill="${bg}" />
      <circle cx="320" cy="240" r="110" fill="#fff7ea" opacity="0.92" />
      <path d="M170 520c26-94 95-142 150-142s124 48 150 142" fill="#fff7ea" opacity="0.92" />
      <text x="320" y="590" text-anchor="middle" font-size="72" font-family="Georgia, serif" fill="#173f33" font-weight="700">${initials}</text>
    </svg>
  `;

  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

const previewStudents = [
  ["K. Maheshwari", "K. Narsimha", "female", "B.Sc Agriculture", "Student"],
  ["R. Srinivas", "R. Laxman", "male", "Diploma", "Farmer"],
  ["A. Padmavathi", "A. Mallaiah", "female", "Intermediate", "Trainee"],
  ["M. Harish", "M. Rajaiah", "male", "B.Com", "Entrepreneur"],
  ["S. Keerthana", "S. Ramesh", "female", "Degree", "Student"],
  ["P. Venkatesh", "P. Krishna", "male", "ITI", "Worker"],
  ["G. Revathi", "G. Anjaneyulu", "female", "B.Sc", "Student"],
  ["T. Naveen", "T. Satyam", "male", "Intermediate", "Farmer"],
  ["Y. Soujanya", "Y. Narender", "female", "MBA", "Coordinator"],
  ["D. Suresh", "D. Lingaiah", "male", "Degree", "Farmer"],
  ["B. Lavanya", "B. Balaraju", "female", "B.Tech", "Student"],
  ["C. Mahender", "C. Gopal", "male", "Diploma", "Field assistant"],
  ["N. Bhavani", "N. Yadagiri", "female", "Intermediate", "Student"],
  ["V. Karthik", "V. Janardhan", "male", "B.Sc", "Farmer"],
  ["J. Aruna", "J. Prabhakar", "female", "Degree", "Self-help group member"],
  ["L. Rakesh", "L. Malla Reddy", "male", "BBA", "Entrepreneur"],
  ["H. Deepika", "H. Narasimulu", "female", "M.Sc", "Trainer"],
  ["E. Rajesh", "E. Ashok", "male", "Intermediate", "Student"],
  ["U. Meghana", "U. Sathish", "female", "B.Pharmacy", "Student"],
  ["Q. Pradeep", "Q. Venkanna", "male", "Degree", "Farmer"],
  ["K. Tejaswini", "K. Tirupathi", "female", "B.Sc Zoology", "Student"],
  ["R. Bhargav", "R. Sadanandam", "male", "MBA", "Business owner"],
  ["A. Niharika", "A. Devender", "female", "Intermediate", "Trainee"],
  ["M. Yashwanth", "M. Narayana", "male", "B.Tech", "Student"],
  ["S. Haripriya", "S. Srinivasulu", "female", "Degree", "Coordinator"],
  ["P. Chandu", "P. Nagesh", "male", "ITI", "Mechanic"],
  ["G. Sirisha", "G. Yellaiah", "female", "B.A.", "Student"],
  ["T. Kiran", "T. Veeraiah", "male", "Intermediate", "Farmer"],
  ["Y. Divya", "Y. Shankar", "female", "B.Com", "Student"],
  ["D. Naresh", "D. Bikshapathi", "male", "Degree", "Field assistant"],
] as const;

const previewBatches = [
  {
    code: "BK-26-07",
    serviceName: "Beekeeping",
    district: "Hyderabad",
    mandal: "Rajendranagar",
    pinCode: "500030",
    baseDate: new Date("2026-06-03T08:15:00.000Z"),
    color: "#d89a11",
  },
  {
    code: "QR-26-08",
    serviceName: "Queen Rearing & Colony Multiplication",
    district: "Ranga Reddy",
    mandal: "Shamshabad",
    pinCode: "501218",
    baseDate: new Date("2026-06-08T11:20:00.000Z"),
    color: "#7a5a00",
  },
  {
    code: "BK-26-09",
    serviceName: "Beekeeping",
    district: "Ranga Reddy",
    mandal: "Maheshwaram",
    pinCode: "501359",
    baseDate: new Date("2026-06-10T07:55:00.000Z"),
    color: "#21533f",
  },
] as const;

export const fallbackApplications = previewStudents.map((student, index) => {
  const [candidateName, guardianName, gender, educationQualification, occupation] = student;
  const batch = previewBatches[Math.floor(index / 10)];
  const batchIndex = index % 10;
  const sequence = String(index + 1).padStart(2, "0");
  const initials = candidateName
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
  const attemptedAt = new Date(batch.baseDate.getTime() + batchIndex * 86_400_000);
  const submittedAt = new Date(attemptedAt.getTime() + 25 * 60 * 1000);
  const isApproved = batchIndex < 4;
  const isPaymentPending = batchIndex >= 4 && batchIndex < 7;
  const paymentStatus = isApproved ? "PAID" : isPaymentPending ? "PENDING" : "NOT_STARTED";
  const approvalStatus = isApproved ? "APPROVED" : batchIndex === 9 ? "REJECTED" : "PENDING";
  const crossCheckStatus = batchIndex < 7 ? "VERIFIED" : "PENDING";
  const attemptStatus =
    paymentStatus === "PAID"
      ? "PAYMENT_COMPLETED"
      : paymentStatus === "PENDING"
        ? "PAYMENT_INITIATED"
        : batchIndex > 7
          ? "ATTEMPTED"
          : "SUBMITTED";
  const approvedAt = isApproved ? new Date(submittedAt.getTime() + 2 * 86_400_000).toISOString() : null;
  const phone = `93${String(95500000 + index * 137).slice(-8)}`;
  const emailSlug = candidateName.toLowerCase().replace(/[^a-z]+/g, ".").replace(/^\.+|\.+$/g, "");

  return {
    id: `app-preview-${sequence}`,
    createdAt: attemptedAt.toISOString(),
    updatedAt: (approvedAt ? new Date(approvedAt) : submittedAt).toISOString(),
    name: candidateName,
    email: `${emailSlug}.preview@apiculture.in`,
    phone,
    payload: {
      version: 2 as const,
      serviceName: batch.serviceName,
      applicationDate: attemptedAt.toISOString().slice(0, 10),
      candidateName,
      guardianName,
      email: `${emailSlug}.preview@apiculture.in`,
      gender: gender as "male" | "female",
      dateOfBirth: `20${String(1 + (index % 5)).padStart(2, "0")}-${String(1 + (index % 12)).padStart(2, "0")}-${String(10 + (index % 18)).padStart(2, "0")}`,
      addressLine: `H.No. ${4 + batchIndex}-${80 + batchIndex}, Preview Street`,
      mandal: batch.mandal,
      district: batch.district,
      state: "Telangana",
      pinCode: batch.pinCode,
      phone,
      residencePhone: batchIndex % 3 === 0 ? "04024017766" : "",
      educationQualification,
      occupation,
      sponsoringOrganization: batchIndex % 2 === 0 ? "Women SHG Cluster" : "Rural Youth Club",
      photoName: `${emailSlug}-photo.png`,
      photoType: "image/png",
      photoDataUrl: createStudentPhotoDataUri(initials, batch.color),
      attemptStatus: attemptStatus as "ATTEMPTED" | "SUBMITTED" | "PAYMENT_INITIATED" | "PAYMENT_FAILED" | "PAYMENT_COMPLETED",
      paymentStatus: paymentStatus as "NOT_STARTED" | "PENDING" | "PAID" | "FAILED",
      approvalStatus: approvalStatus as "PENDING" | "APPROVED" | "REJECTED",
      crossCheckStatus: crossCheckStatus as "PENDING" | "VERIFIED",
      attemptedAt: attemptedAt.toISOString(),
      submittedAt: submittedAt.toISOString(),
      approvedAt,
      approvedBy: isApproved ? "Preview Admin" : null,
      adminNotes: `Preview student assigned to Batch ${batch.code}.`,
      paymentReference: paymentStatus === "PAID" ? `UPI-${batch.code.replaceAll("-", "")}-${sequence}` : paymentStatus === "PENDING" ? `BANK-${batch.code.replaceAll("-", "")}-${sequence}` : "",
    },
  };
});
